# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info_file.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='info_file.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0finfo_file.proto\"\x91\x01\n\x0c\x44\x61tabaseInfo\x12\x19\n\x11number_of_classes\x18\x01 \x01(\r\x12\x37\n\x10\x63lass_dictionary\x18\x02 \x03(\x0b\x32\x1d.DatabaseInfo.ClassDictionary\x1a-\n\x0f\x43lassDictionary\x12\x0b\n\x03key\x18\x01 \x03(\x04\x12\r\n\x05value\x18\x02 \x03(\x05\x62\x06proto3')
)




_DATABASEINFO_CLASSDICTIONARY = _descriptor.Descriptor(
  name='ClassDictionary',
  full_name='DatabaseInfo.ClassDictionary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='DatabaseInfo.ClassDictionary.key', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='DatabaseInfo.ClassDictionary.value', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=165,
)

_DATABASEINFO = _descriptor.Descriptor(
  name='DatabaseInfo',
  full_name='DatabaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number_of_classes', full_name='DatabaseInfo.number_of_classes', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='class_dictionary', full_name='DatabaseInfo.class_dictionary', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_DATABASEINFO_CLASSDICTIONARY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=165,
)

_DATABASEINFO_CLASSDICTIONARY.containing_type = _DATABASEINFO
_DATABASEINFO.fields_by_name['class_dictionary'].message_type = _DATABASEINFO_CLASSDICTIONARY
DESCRIPTOR.message_types_by_name['DatabaseInfo'] = _DATABASEINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DatabaseInfo = _reflection.GeneratedProtocolMessageType('DatabaseInfo', (_message.Message,), dict(

  ClassDictionary = _reflection.GeneratedProtocolMessageType('ClassDictionary', (_message.Message,), dict(
    DESCRIPTOR = _DATABASEINFO_CLASSDICTIONARY,
    __module__ = 'info_file_pb2'
    # @@protoc_insertion_point(class_scope:DatabaseInfo.ClassDictionary)
    ))
  ,
  DESCRIPTOR = _DATABASEINFO,
  __module__ = 'info_file_pb2'
  # @@protoc_insertion_point(class_scope:DatabaseInfo)
  ))
_sym_db.RegisterMessage(DatabaseInfo)
_sym_db.RegisterMessage(DatabaseInfo.ClassDictionary)


# @@protoc_insertion_point(module_scope)
