# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: midi.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='midi.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\nmidi.proto\"\x88\x06\n\x0cMidiDatabase\x12)\n\tmidi_song\x18\x01 \x03(\x0b\x32\x16.MidiDatabase.MidiSong\x1a\xcc\x05\n\x08MidiSong\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\x11\n\tfile_name\x18\x03 \x01(\x0c\x12\x11\n\tfile_time\x18\x04 \x01(\r\x12\x0b\n\x03PPQ\x18\x05 \x01(\x05\x12+\n\x05track\x18\x06 \x03(\x0b\x32\x1c.MidiDatabase.MidiSong.Track\x1a\xc0\x04\n\x05Track\x12\x14\n\x0ctrack_number\x18\x01 \x01(\r\x12\x31\n\x05tempo\x18\x02 \x03(\x0b\x32\".MidiDatabase.MidiSong.Track.Tempo\x12\x42\n\x0etime_signature\x18\x03 \x03(\x0b\x32*.MidiDatabase.MidiSong.Track.TimeSignature\x12@\n\rkey_signature\x18\x04 \x03(\x0b\x32).MidiDatabase.MidiSong.Track.KeySignature\x12\x30\n\x05notes\x18\x05 \x03(\x0b\x32!.MidiDatabase.MidiSong.Track.Note\x1a*\n\x05Tempo\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x13\n\x0btempo_value\x18\x02 \x01(\r\x1a\x45\n\rTimeSignature\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x11\n\tnumerator\x18\x02 \x01(\r\x12\x13\n\x0b\x64\x65nominator\x18\x03 \x01(\r\x1a\x37\n\x0cKeySignature\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12\x0b\n\x03key\x18\x02 \x01(\r\x12\x0c\n\x04mode\x18\x03 \x01(\r\x1a\x89\x01\n\x04Note\x12\r\n\x05pitch\x18\x01 \x01(\r\x12\x10\n\x08velocity\x18\x02 \x01(\r\x12\x14\n\x0cstart_time_s\x18\x03 \x01(\x01\x12\x12\n\nstart_time\x18\x04 \x01(\r\x12\x12\n\nend_time_s\x18\x05 \x01(\x01\x12\x10\n\x08\x65nd_time\x18\x06 \x01(\r\x12\x10\n\x08\x64uration\x18\x07 \x01(\x01\x62\x06proto3')
)




_MIDIDATABASE_MIDISONG_TRACK_TEMPO = _descriptor.Descriptor(
  name='Tempo',
  full_name='MidiDatabase.MidiSong.Track.Tempo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='MidiDatabase.MidiSong.Track.Tempo.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tempo_value', full_name='MidiDatabase.MidiSong.Track.Tempo.tempo_value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=481,
  serialized_end=523,
)

_MIDIDATABASE_MIDISONG_TRACK_TIMESIGNATURE = _descriptor.Descriptor(
  name='TimeSignature',
  full_name='MidiDatabase.MidiSong.Track.TimeSignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='MidiDatabase.MidiSong.Track.TimeSignature.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='numerator', full_name='MidiDatabase.MidiSong.Track.TimeSignature.numerator', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='denominator', full_name='MidiDatabase.MidiSong.Track.TimeSignature.denominator', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=525,
  serialized_end=594,
)

_MIDIDATABASE_MIDISONG_TRACK_KEYSIGNATURE = _descriptor.Descriptor(
  name='KeySignature',
  full_name='MidiDatabase.MidiSong.Track.KeySignature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time', full_name='MidiDatabase.MidiSong.Track.KeySignature.time', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='MidiDatabase.MidiSong.Track.KeySignature.key', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='MidiDatabase.MidiSong.Track.KeySignature.mode', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=596,
  serialized_end=651,
)

_MIDIDATABASE_MIDISONG_TRACK_NOTE = _descriptor.Descriptor(
  name='Note',
  full_name='MidiDatabase.MidiSong.Track.Note',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pitch', full_name='MidiDatabase.MidiSong.Track.Note.pitch', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='MidiDatabase.MidiSong.Track.Note.velocity', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_time_s', full_name='MidiDatabase.MidiSong.Track.Note.start_time_s', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='MidiDatabase.MidiSong.Track.Note.start_time', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time_s', full_name='MidiDatabase.MidiSong.Track.Note.end_time_s', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='end_time', full_name='MidiDatabase.MidiSong.Track.Note.end_time', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='duration', full_name='MidiDatabase.MidiSong.Track.Note.duration', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=654,
  serialized_end=791,
)

_MIDIDATABASE_MIDISONG_TRACK = _descriptor.Descriptor(
  name='Track',
  full_name='MidiDatabase.MidiSong.Track',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='track_number', full_name='MidiDatabase.MidiSong.Track.track_number', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tempo', full_name='MidiDatabase.MidiSong.Track.tempo', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_signature', full_name='MidiDatabase.MidiSong.Track.time_signature', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key_signature', full_name='MidiDatabase.MidiSong.Track.key_signature', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notes', full_name='MidiDatabase.MidiSong.Track.notes', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MIDIDATABASE_MIDISONG_TRACK_TEMPO, _MIDIDATABASE_MIDISONG_TRACK_TIMESIGNATURE, _MIDIDATABASE_MIDISONG_TRACK_KEYSIGNATURE, _MIDIDATABASE_MIDISONG_TRACK_NOTE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=791,
)

_MIDIDATABASE_MIDISONG = _descriptor.Descriptor(
  name='MidiSong',
  full_name='MidiDatabase.MidiSong',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MidiDatabase.MidiSong.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_path', full_name='MidiDatabase.MidiSong.file_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_name', full_name='MidiDatabase.MidiSong.file_name', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='file_time', full_name='MidiDatabase.MidiSong.file_time', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='PPQ', full_name='MidiDatabase.MidiSong.PPQ', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='track', full_name='MidiDatabase.MidiSong.track', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MIDIDATABASE_MIDISONG_TRACK, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=791,
)

_MIDIDATABASE = _descriptor.Descriptor(
  name='MidiDatabase',
  full_name='MidiDatabase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='midi_song', full_name='MidiDatabase.midi_song', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_MIDIDATABASE_MIDISONG, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=791,
)

_MIDIDATABASE_MIDISONG_TRACK_TEMPO.containing_type = _MIDIDATABASE_MIDISONG_TRACK
_MIDIDATABASE_MIDISONG_TRACK_TIMESIGNATURE.containing_type = _MIDIDATABASE_MIDISONG_TRACK
_MIDIDATABASE_MIDISONG_TRACK_KEYSIGNATURE.containing_type = _MIDIDATABASE_MIDISONG_TRACK
_MIDIDATABASE_MIDISONG_TRACK_NOTE.containing_type = _MIDIDATABASE_MIDISONG_TRACK
_MIDIDATABASE_MIDISONG_TRACK.fields_by_name['tempo'].message_type = _MIDIDATABASE_MIDISONG_TRACK_TEMPO
_MIDIDATABASE_MIDISONG_TRACK.fields_by_name['time_signature'].message_type = _MIDIDATABASE_MIDISONG_TRACK_TIMESIGNATURE
_MIDIDATABASE_MIDISONG_TRACK.fields_by_name['key_signature'].message_type = _MIDIDATABASE_MIDISONG_TRACK_KEYSIGNATURE
_MIDIDATABASE_MIDISONG_TRACK.fields_by_name['notes'].message_type = _MIDIDATABASE_MIDISONG_TRACK_NOTE
_MIDIDATABASE_MIDISONG_TRACK.containing_type = _MIDIDATABASE_MIDISONG
_MIDIDATABASE_MIDISONG.fields_by_name['track'].message_type = _MIDIDATABASE_MIDISONG_TRACK
_MIDIDATABASE_MIDISONG.containing_type = _MIDIDATABASE
_MIDIDATABASE.fields_by_name['midi_song'].message_type = _MIDIDATABASE_MIDISONG
DESCRIPTOR.message_types_by_name['MidiDatabase'] = _MIDIDATABASE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MidiDatabase = _reflection.GeneratedProtocolMessageType('MidiDatabase', (_message.Message,), dict(

  MidiSong = _reflection.GeneratedProtocolMessageType('MidiSong', (_message.Message,), dict(

    Track = _reflection.GeneratedProtocolMessageType('Track', (_message.Message,), dict(

      Tempo = _reflection.GeneratedProtocolMessageType('Tempo', (_message.Message,), dict(
        DESCRIPTOR = _MIDIDATABASE_MIDISONG_TRACK_TEMPO,
        __module__ = 'midi_pb2'
        # @@protoc_insertion_point(class_scope:MidiDatabase.MidiSong.Track.Tempo)
        ))
      ,

      TimeSignature = _reflection.GeneratedProtocolMessageType('TimeSignature', (_message.Message,), dict(
        DESCRIPTOR = _MIDIDATABASE_MIDISONG_TRACK_TIMESIGNATURE,
        __module__ = 'midi_pb2'
        # @@protoc_insertion_point(class_scope:MidiDatabase.MidiSong.Track.TimeSignature)
        ))
      ,

      KeySignature = _reflection.GeneratedProtocolMessageType('KeySignature', (_message.Message,), dict(
        DESCRIPTOR = _MIDIDATABASE_MIDISONG_TRACK_KEYSIGNATURE,
        __module__ = 'midi_pb2'
        # @@protoc_insertion_point(class_scope:MidiDatabase.MidiSong.Track.KeySignature)
        ))
      ,

      Note = _reflection.GeneratedProtocolMessageType('Note', (_message.Message,), dict(
        DESCRIPTOR = _MIDIDATABASE_MIDISONG_TRACK_NOTE,
        __module__ = 'midi_pb2'
        # @@protoc_insertion_point(class_scope:MidiDatabase.MidiSong.Track.Note)
        ))
      ,
      DESCRIPTOR = _MIDIDATABASE_MIDISONG_TRACK,
      __module__ = 'midi_pb2'
      # @@protoc_insertion_point(class_scope:MidiDatabase.MidiSong.Track)
      ))
    ,
    DESCRIPTOR = _MIDIDATABASE_MIDISONG,
    __module__ = 'midi_pb2'
    # @@protoc_insertion_point(class_scope:MidiDatabase.MidiSong)
    ))
  ,
  DESCRIPTOR = _MIDIDATABASE,
  __module__ = 'midi_pb2'
  # @@protoc_insertion_point(class_scope:MidiDatabase)
  ))
_sym_db.RegisterMessage(MidiDatabase)
_sym_db.RegisterMessage(MidiDatabase.MidiSong)
_sym_db.RegisterMessage(MidiDatabase.MidiSong.Track)
_sym_db.RegisterMessage(MidiDatabase.MidiSong.Track.Tempo)
_sym_db.RegisterMessage(MidiDatabase.MidiSong.Track.TimeSignature)
_sym_db.RegisterMessage(MidiDatabase.MidiSong.Track.KeySignature)
_sym_db.RegisterMessage(MidiDatabase.MidiSong.Track.Note)


# @@protoc_insertion_point(module_scope)
